### ISSUE TITLE
make fails with DHAVE_CONFIG_H: command not found when AX_PTHREAD: command not found

### ISSUE THREAD

**Issue by a3f** [pengutronix/microcom#8]
On Debian Stretch, the `autoconf-archive` package is required to supply `ax_pthread.m4`.
Without that package installed, `./configure` will print an easily missed

```
./configure: line 3924: AX_PTHREAD: command not found
```

warning early on, but won't fail. Running `make` afterwards results in
```
DHAVE_CONFIG_H: command not found
```

because `CC="$PTHREAD_CC"` whenever `--disable-can` is unspecified.

I am not sure what's the proper way to avoid this. One could:

* Readd `m4/ax_pthread.m4` to the repository, it was removed in c25e6d472086cd96adfb1d3416225bca508d6baa
* check with `m4_ifdef`, but that requires Autotools 2.63
* Add an `autogen.sh` script that checks for `/usr/share/aclocal/ax_pthread.m4`
* Something else I am missing? (I am configuring with `autoreconf --install --symlink`)

I can open a PR with the needed changes, what should I do?

**Comment by ukleinek** [comment]
Hello Ahmad,

\> because `CC="$PTHREAD_CC"` whenever `--disable-can` is unspecified.

I wonder if this line is correct. Actually I don't like this pthread detection code and the right thing would be to get rid of the dependency on pthreads. This would result in a redesign of microcom's datamodel or can must be dropped.

> I am not sure what's the proper way to avoid this. One could:
> 
>     * Readd `m4/ax_pthread.m4` to the repository, it was removed in [c25e6d4](https://github.com/pengutronix/microcom/commit/c25e6d472086cd96adfb1d3416225bca508d6baa)

I removed it because it annoyed during testing. If on different machines different versions of autoconf-archive are installed which include different versions of ax_pthread.m4 there are on at least one of the machines dirty changes.

>     * check with `m4_ifdef`, but that requires Autotools 2.63

We already have AC_PREREQ([2.69]), so this should be fine. `m4_pattern_forbid` is nicer though.

>     * Add an `autogen.sh` script that checks for `/usr/share/aclocal/ax_pthread.m4`

Checking for this path is broken. A better option would be to check if after autoreconf `m4/ax_pthread.m4` exists, but this isn't optimal either, because this hardcodes the name of the file that defines AX_PTHREAD.

>     * Something else I am missing? (I am configuring with `autoreconf --install --symlink`)

Yeah, you're missing [`m4_pattern_forbid`](https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Forbidden-Patterns.html). Care to test/review my change on your end?

Thanks
Uwe

**Comment by rohieb** [comment]
This issue should have been closed via commit a13e6e68fcd9ed17. Also we now list the autoconf archive as a dependency in README, so ax_pthread.m4 should always be found in /usr/share/aclocal/.

**Comment by rohieb** [comment]
Wait, sorry, I'm confused by GitHub's interface. a13e6e68 is not in master yet, but I also cannot find it in any branch…?

While I still consider this bug done with the mentioned change to README, I think we should still warn if the macro is missing.

**Comment by rohieb** [comment]
Ah, it's in https://github.com/ukleinek/microcom/tree/ukl/axpthread, of course.

I tested that commit, but it errors:

``` console
$ autoreconf -i
configure:4477: error: possibly undefined macro: AX_PTHREAD_ZOS_MISSING
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:4547: error: possibly undefined macro: AX_PTHREAD_CC_IS_CLANG
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

This is because ax_pthread.m4 does some magic to determine at ./configure runtime whether these values have been expanded:

``` console
$ grep -n -A2 -B4 AX_PTHREAD_ configure
4473-        cat confdefs.h - <<_ACEOF >conftest.$ac_ext
4474-/* end confdefs.h.  */
4475-
4476-#            if !defined(_OPEN_THREADS) && !defined(_UNIX03_THREADS)
4477:             AX_PTHREAD_ZOS_MISSING
4478-#            endif
4479-
4480-_ACEOF
4481-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
4482:  $EGREP "AX_PTHREAD_ZOS_MISSING" >/dev/null 2>&1; then :
4483-  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: IBM z/OS requires -D_OPEN_THREADS or -D_UNIX03_THREADS to enable pthreads support." >&5
4484-$as_echo "$as_me: WARNING: IBM z/OS requires -D_OPEN_THREADS or -D_UNIX03_THREADS to enable pthreads support." >&2;}
--
4543-        cat confdefs.h - <<_ACEOF >conftest.$ac_ext
4544-/* end confdefs.h.  */
4545-/* Note: Clang 2.7 lacks __clang_[a-z]+__ */
4546-#            if defined(__clang__) && defined(__llvm__)
4547:             AX_PTHREAD_CC_IS_CLANG
4548-#            endif
4549-
4550-_ACEOF
4551-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
4552:  $EGREP "AX_PTHREAD_CC_IS_CLANG" >/dev/null 2>&1; then :
4553-  ax_cv_PTHREAD_CLANG=yes
4554-fi
```

It seems to me that `^AX_PTHREAD` is not only matching at start-of-line, but also at start-of-line-followed-by-whitespace.

**Comment by rohieb** [comment]
`m4_pattern_forbid([^AX_PTHREAD$])` seems to work though, because we don't need to pass any arguments to `AX_PTHREAD`. To test the negative case, I added a simple line that produces a literal `AC_PTHREAD` in the output:

``` console
$ git diff; rm -r m4/; autoreconf -i
diff --git a/configure.ac b/configure.ac
index bbcc705..7e40c74 100644
--- a/configure.ac
+++ b/configure.ac
@@ -6,7 +6,8 @@ AM_INIT_AUTOMAKE([dist-xz])
 dnl If autoconf-archive isn't installed the macro AX_PTHREAD might be undefined
 dnl and make it into configure. This breaks the generated Makefile, so detect
 dnl this at autoconf time.
-m4_pattern_forbid([^AX_PTHREAD])
+m4_pattern_forbid([^AX_PTHREAD$])
+AX_[]PTHREAD
 
 AC_PREREQ([2.69])
 AC_CONFIG_SRCDIR([commands_fsl_imx.c])
aclocal: installing 'm4/ax_pthread.m4' from '/usr/share/aclocal/ax_pthread.m4'
configure.ac:6: error: possibly undefined macro: AX_PTHREAD
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

Also I would suggest to move the `m4_pattern_forbid()` call directly next to the `AX_PTHREAD` call so it doesn't get lost if our configure.ac should grow bigger :)
